/**
 * Route tree generation
 * Auto-generated file - do not edit manually
 * Generated by TanStack Router
 */

import { Route as rootRoute } from './__root'
import { Route as AccountsRoute } from './accounts'
import { Route as BudgetsRoute } from './budgets'
import { Route as DashboardRoute } from './dashboard'
import { Route as GoalsRoute } from './goals'
import { Route as IndexRoute } from './index'
import { Route as ReportsRoute } from './reports'
import { Route as SettingsRoute } from './settings'
import { Route as TransactionsRoute } from './transactions'

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
    '/accounts': {
      preLoaderRoute: typeof AccountsRoute
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      preLoaderRoute: typeof DashboardRoute
      parentRoute: typeof rootRoute
    }
    '/transactions': {
      preLoaderRoute: typeof TransactionsRoute
      parentRoute: typeof rootRoute
    }
    '/budgets': {
      preLoaderRoute: typeof BudgetsRoute
      parentRoute: typeof rootRoute
    }
    '/goals': {
      preLoaderRoute: typeof GoalsRoute
      parentRoute: typeof rootRoute
    }
    '/reports': {
      preLoaderRoute: typeof ReportsRoute
      parentRoute: typeof rootRoute
    }
    '/settings': {
      preLoaderRoute: typeof SettingsRoute
      parentRoute: typeof rootRoute
    }
  }
}

Object.assign(IndexRoute.options, {
  path: '/',
})

Object.assign(AccountsRoute.options, {
  path: '/accounts',
})

Object.assign(DashboardRoute.options, {
  path: '/dashboard',
})

Object.assign(TransactionsRoute.options, {
  path: '/transactions',
})

Object.assign(BudgetsRoute.options, {
  path: '/budgets',
})

Object.assign(GoalsRoute.options, {
  path: '/goals',
})

Object.assign(ReportsRoute.options, {
  path: '/reports',
})

Object.assign(SettingsRoute.options, {
  path: '/settings',
})

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AccountsRoute,
  DashboardRoute,
  TransactionsRoute,
  BudgetsRoute,
  GoalsRoute,
  ReportsRoute,
  SettingsRoute,
])
