packages:
  - packages/*

catalog:
  '@biomejs/biome': ^2.2.7
  '@types/node': ^24.9.1
  concurrently: ^9.2.1
  firebase: ^12.4.0
  firebase-admin: ^13.5.0
  firebase-tools: ^14.21.0
  firebase-functions: ^6.6.0
  typescript: ^5.9.3
