#!/bin/bash

# Script to add macOS target to wealth-wise.xcodeproj
# This script provides instructions for manually adding the macOS target in Xcode

echo "🍎 WealthWise macOS Target Setup Instructions"
echo "============================================="
echo ""
echo "To add the macOS target to the existing wealth-wise.xcodeproj:"
echo ""
echo "1. Open Xcode and navigate to apple/wealth-wise/wealth-wise.xcodeproj"
echo ""
echo "2. Select the project name in the navigator (top-level)"
echo ""
echo "3. Click the '+' button at the bottom of the targets list"
echo ""
echo "4. Choose 'macOS' > 'App' and click Next"
echo ""
echo "5. Configure the target:"
echo "   - Product Name: WealthWise"
echo "   - Bundle Identifier: com.wealthwise.macos"
echo "   - Language: Swift"
echo "   - Interface: SwiftUI"
echo "   - Use Core Data: Yes (or SwiftData)"
echo "   - Include Tests: Yes"
echo ""
echo "6. Choose the project location and create the target"
echo ""
echo "7. After target creation:"
echo "   a. Delete the auto-generated ContentView.swift and App.swift files"
echo "   b. Add the files from macOS/ and Shared/ directories to the new target"
echo "   c. Ensure shared files (ContentView.swift, Item.swift) are added to both targets"
echo ""
echo "8. Configure target settings:"
echo "   - Deployment Target: macOS 14.0"
echo "   - Supported Destinations: Mac"
echo "   - Localizations: Add English (en) and Hindi (hi) in project settings"
echo ""
echo "9. Build and test both targets to ensure everything works"
echo ""
echo "📁 Files to add to macOS target:"
echo "   - macOS/WealthWiseMacApp.swift (main app file)"
echo "   - macOS/MacContentView.swift (macOS UI)"
echo "   - macOS/Info.plist (configuration)"
echo "   - Shared/DataModels.swift (data models)"
echo "   - Shared/LocalizationHelpers.swift (localization support)"
echo "   - Shared/Resources/ (localization files - add to both targets)"
echo "   - wealth-wise/ContentView.swift (shared, add to both targets)"
echo "   - wealth-wise/Item.swift (shared, add to both targets)"
echo ""
echo "✅ Once completed, you'll have both iOS and macOS targets in one project!"
echo ""
echo "To run this setup:"
echo "1. cd apple/wealth-wise"
echo "2. open wealth-wise.xcodeproj"
echo "3. Follow the instructions above"
echo ""

# Check if we're in the right directory
if [ -f "wealth-wise.xcodeproj/project.pbxproj" ]; then
    echo "✅ Found Xcode project in current directory"
    echo "📂 Opening Xcode project..."
    open wealth-wise.xcodeproj
else
    echo "❌ Please run this script from apple/wealth-wise/ directory"
    echo "Current directory: $(pwd)"
    echo "Expected to find: wealth-wise.xcodeproj/project.pbxproj"
fi